language: R
r:
    - oldrel

cache: packages
pandoc_version: 2.3.1

repos:
    MRAN: "https://mran.microsoft.com/snapshot/2019-08-02"
  
warnings_are_errors: false

script:
- Rscript -e 'bookdown::render_book("original_book/index.Rmd")'